### ISSUE TITLE
RustBridge Waterloo

### ISSUE THREAD

**Issue by ashleygwilliams** [rustbridge/team#1] opened 2018-01-15 14:24 UTC
- lead: @arshiamufti
- Saturday March 17, 10am-5pm

**Comment by arshiamufti** [comment] 2018-02-20 16:53
- Date is confirmed for Saturday March 17, we will aim to start at 10 am and wrap up by 5 pm (though this time frame might change over the next few weeks.
- A room has been booked at the University of Waterloo.
- Two other members of the rust community (Sunjay and Josh)
 will be helping out and present on the day of
- An [Eventbrite](https://www.eventbrite.com/e/rustbridge-waterloo-registration-43330749438) page has been created.

next:
- promote event on the rustlang/rustbridge twitter
- promote event on this week in rust (maybe?)
- promote event within waterloo FB groups/online spaces
- improve slides and discuss content with Josh/Sunjay (we're going to look at the experience level of registered people and go from there)

**Comment by arshiamufti** [comment] 2018-02-20 17:02
@ashleygwilliams if you have a sec to look at the Eventbrite, I'd appreciate it :)

**Comment by ashleygwilliams** [comment] 2018-02-20 17:07
@arshiamufti this looks great! we should add this info to the website! i'll add you to the github now. lemme know if you'd like to make the PR or if i should!

**Comment by arshiamufti** [comment] 2018-02-20 17:08
i can do it by eod

**Comment by ghost** [comment] 2018-05-22 09:59
Closing this since it happened quite some time ago!

**Closed as completed by ghost** 2018-05-22 09:59 UTC
